// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segundo_parcial_Josmeyly.DAL;

#nullable disable

namespace Segundo_parcial_Josmeyly.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250318042700_tercera")]
    partial class tercera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.Ciudades", b =>
                {
                    b.Property<int>("CiudadesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadesId"));

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadesId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadesId = 1,
                            Monto = 0.0,
                            Nombres = "Villa Arriba"
                        },
                        new
                        {
                            CiudadesId = 2,
                            Monto = 0.0,
                            Nombres = "San francisco"
                        },
                        new
                        {
                            CiudadesId = 3,
                            Monto = 0.0,
                            Nombres = "San Pedro de macoris"
                        });
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.DetalleCiudad", b =>
                {
                    b.Property<int>("DetalleCiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCiudadId"));

                    b.Property<int?>("CiudadesId")
                        .HasColumnType("int");

                    b.Property<int?>("CiudadesId1")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<double>("MontoCuenta")
                        .HasColumnType("float");

                    b.HasKey("DetalleCiudadId");

                    b.HasIndex("CiudadesId");

                    b.HasIndex("CiudadesId1");

                    b.HasIndex("EncuestaId");

                    b.ToTable("DetalleCiudad");
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.Encuesta", b =>
                {
                    b.Property<int>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncuestaId"));

                    b.Property<string>("Asignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CiudadesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("EncuestaId");

                    b.HasIndex("CiudadesId");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.DetalleCiudad", b =>
                {
                    b.HasOne("Segundo_parcial_Josmeyly.Models.Encuesta", null)
                        .WithMany("DetalleCiudad")
                        .HasForeignKey("CiudadesId");

                    b.HasOne("Segundo_parcial_Josmeyly.Models.Ciudades", null)
                        .WithMany("DetalleCiudad")
                        .HasForeignKey("CiudadesId1");

                    b.HasOne("Segundo_parcial_Josmeyly.Models.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.Encuesta", b =>
                {
                    b.HasOne("Segundo_parcial_Josmeyly.Models.Ciudades", "Ciudades")
                        .WithMany("Encuesta")
                        .HasForeignKey("CiudadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.Ciudades", b =>
                {
                    b.Navigation("DetalleCiudad");

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("Segundo_parcial_Josmeyly.Models.Encuesta", b =>
                {
                    b.Navigation("DetalleCiudad");
                });
#pragma warning restore 612, 618
        }
    }
}
